name: CI/CD Deploy (Quiz App)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push API Image
        uses: docker/build-push-action@v6
        with:
          context: ./quiz-app-server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quiz-api:latest

      - name: Build & Push Client Image
        uses: docker/build-push-action@v6
        with:
          context: ./quiz-app-client
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quiz-client:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -e
            REPO_DIR="$HOME/My_Quiz_App"

            # Clone once if not present
            if [ ! -d "$REPO_DIR/.git" ]; then
              git clone https://github.com/SUJAL-7/My_Quiz_App.git "$REPO_DIR"
            fi

            cd "$REPO_DIR"
            git checkout main
            git pull --ff-only

            # Expect quiz-app-server/.env already exists (you manage it manually)
            if [ ! -f quiz-app-server/.env ]; then
              echo "ERROR: quiz-app-server/.env missing on server. Create it before running containers."
              exit 1
            fi

            docker compose pull || true
            docker compose up -d
            docker compose ps